#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication topoSet

runApplication createBaffles -overwrite

rm -rf 0 && cp -r 0_org 0

# runApplication decomposePar

#runApplication pimpleFoam  
